src/Entity/Blog/Post.php
<?php

declare(strict_types=1);

namespace App\Entity\Blog;

use App\Entity\Hru;
use App\Entity\User;
use App\Form\Blog\PostDTO;
use App\Repository\Blog\PostRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\Table;

#[Entity(repositoryClass: PostRepository::class)]
#[Table(name: "posts")]
class Post
{
    #[Id]
    #[GeneratedValue(strategy: "AUTO")]
    #[Column(type: "integer")]
    private int $id;

    #[Column(type: "string")]
    private string $title;

    #[Column(type: "text")]
    private string $body;

    #[Column(type: "datetime_immutable")]
    private \DateTimeImmutable $created;

    #[ManyToOne(targetEntity: Section::class)]
    #[JoinColumn(name: "section_id", referencedColumnName: "id", nullable: false)]
    private Section $section;

    #[ManyToMany(targetEntity: Tag::class, fetch: "EAGER")]
    #[JoinTable(name: "posts_tags")]
    #[JoinColumn(name: "post_id", referencedColumnName: "id")]
    private iterable $tags;

    #[Column(type: "post_status", name: "status", length: 30, nullable: false)]
    private Status $status;

    #[ManyToOne(targetEntity: User::class)]
    #[JoinColumn(name: "author_id", referencedColumnName: "id", nullable: false)]
    private User $author;

    #[Column(type: "text", nullable: true, length: 1000)]
    private ?string $teaser;

    #[ManyToOne(targetEntity: Hru::class, cascade: ["PERSIST"], fetch: "EAGER")]
    #[JoinColumn(name: "hru_id", referencedColumnName: "id", nullable: true)]
    private ?Hru $hru = null;

    public function __construct(
        string $title,
        ?string $teaser,
        \DateTimeImmutable $created,
        string $body,
        Section $section,
        iterable $tags,
        Status $status,
        User $author
    ) {
        $this->title = $title;
        $this->body = $body;
        $this->created = $created;
        $this->section = $section;
        $this->tags = $tags;
        $this->status = $status;
        $this->author = $author;
        $this->teaser = $teaser;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function getBody(): string
    {
        return $this->body;
    }

    public function getCreated(): \DateTimeImmutable
    {
        return $this->created;
    }

    public function getSection(): Section
    {
        return $this->section;
    }

    public function getStatus(): Status
    {
        return $this->status;
    }

    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function getAuthor(): User
    {
        return $this->author;
    }

    public function getTeaser(): ?string
    {
        return $this->teaser;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function updateFieldsByDTO(PostDTO $postDTO): void
    {
        $this->title = $postDTO->title;
        $this->teaser = $postDTO->teaser;
        $this->body = $postDTO->body;
        $this->section = $postDTO->section;
        $this->status = new Status($postDTO->status);
    }

    public function setTags(iterable $tags): void
    {
        $this->tags = $tags;
    }

    public function isPublished(): bool
    {
        return $this->status->isPublished();
    }

    public function isDraft(): bool
    {
        return $this->status->isDraft();
    }

    public function isRemoved(): bool
    {
        return $this->status->isRemoved();
    }

    public function isPrivate(): bool
    {
        return $this->status->isPrivate();
    }

    public function setHru(Hru $hru): void
    {
        if (is_null($this->id)) {
            throw new \DomainException("Id needed for hru. Save post before setting hru.");
        }
        $this->hru = $hru;
        $hru->setEntityId($this->id);
    }

    public function getHru(): ?Hru
    {
        return $this->hru;
    }

    public function setStatus(Status $status): void
    {
        $this->status = $status;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\Table;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[Entity(repositoryClass: UserRepository::class)]
#[Table(name: "users")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[Id]
    #[GeneratedValue(strategy: "AUTO")]
    #[Column(type: "integer")]
    private int $id;

    #[Column(type: "string", length: 180, unique: true)]
    private string $email;

    #[Column(type: "json")]
    private array $roles = [];

    #[Column(type: "string")]
    private ?string $password = null;

    public function __construct(string $email, array $roles)
    {
        $this->email = $email;
        $this->roles = $roles;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/Blog/PostDTO.php
<?php

declare(strict_types=1);

namespace App\Form\Blog;

use App\Entity\Blog\Post;
use App\Entity\Blog\Section;
use App\Entity\Blog\Tag;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints;
use Webmozart\Assert\Assert;

class PostDTO
{
    public string $title = '';
    public ?string $teaser = '';
    public string $body = '';
    /** @var Section */
    public $section;
    public string $status = '';
    /**
     * @Constraints\NotBlank()
     */
    public $tags2 = '';

    public static function createFromPost(Post $post)
    {
        $postDTO = new self();
        $postDTO->title = $post->getTitle();
        $postDTO->teaser = $post->getTeaser();
        $postDTO->body = $post->getBody();
        $postDTO->section = $post->getSection();
        $postDTO->status = $post->getStatus()->getName();
        $postDTO->tags2 = $postDTO->convertToSelectize($post->getTags());

        return $postDTO;
    }

    private function convertToSelectize(Collection $tags): string
    {
        Assert::allIsInstanceOf($tags, Tag::class);
        $tags2 = '';
        /** @var Tag $tag */
        foreach ($tags as $tag) {
            $tags2 .= "{$tag->getId()}^";
        }
        $tags2 = mb_substr($tags2, 0, -1);

        return $tags2;
    }
}

src/Form/Blog/PostForm.php
<?php

declare(strict_types=1);

namespace App\Form\Blog;

use App\Entity\Blog\Section;
use App\Entity\Blog\Status;
use Doctrine\ORM\EntityRepository;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class PostForm extends AbstractType
{
    public function __construct(
        private Security $security
    ) {}

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', TextType::class);

        $builder->add(
            'teaser',
            CKEditorType::class,
            [
                'config' => [
                    'image_previewText' => '',
                    'filebrowserBrowseRoute' => 'elfinder',
                    'filebrowserBrowseRouteParameters' => [
                        'instance' => 'default',
                        'homeFolder' => $this->security->getUser()->getId()
                    ],
                ],
            ]
        );
        $builder->get('teaser')->addModelTransformer(new CallbackTransformer(function ($value) {
                return $value;
        }, function ($value) {
            if (!is_null($value)) {
                return strip_tags($value, '<p><strong><em><s><ol><li><ul><a><blockquote><hr><pre><code><img><table><th><tr><td><tbody><iframe><ul><li><b><span><div><br>');
            }
        }));
        $builder->add(
            'body',
            CKEditorType::class,
            [
                'config' => [
                    'image_previewText' => '',
                    'filebrowserBrowseRoute' => 'elfinder',
                    'filebrowserBrowseRouteParameters' => [
                        'instance' => 'default',
                        'homeFolder' => $this->security->getUser()->getId()
                    ],
                ],
                    ]
        );
        $builder->get('body')->addModelTransformer(new CallbackTransformer(function ($value) {
                return $value;
        }, function ($value) {
            return strip_tags($value, '<p><strong><em><s><ol><li><ul><a><blockquote><hr><pre><code><img><table><th><tr><td><tbody><iframe><ul><li><b><span><div><br>');
        }));
        $builder->add('section', EntityType::class, [
            'class' => Section::class,
            'query_builder' => function (EntityRepository $er) {

                return $er->createQueryBuilder('s')
                    ->where('s.enabled = 1');
            },
        ]);
        $builder->add('tags2', TextType::class, ['required' => true,]);
        $builder->add('status', ChoiceType::class, ['choices' => Status::getConstants()]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => PostDTO::class]);
    }
}

src/Controller/BlogController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Blog\Post;
use App\Entity\Blog\Section;
use App\Entity\Blog\Status;
use App\Entity\Hru;
use App\Form\Blog\PostDTO;
use App\Form\Blog\PostForm;
use App\Repository\Blog\PostRepository;
use App\Repository\Blog\SectionRepository;
use App\Service\Blog\Post\Add;
use App\Service\Blog\Post\Edit;
use App\Service\Blog\Post\Delete;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route("/", name: "blog")]
class BlogController extends AbstractController
{
    #[Route("", name: "", methods: ["GET"])]
    public function list(
        PostRepository $postRepository,
        SectionRepository $sectionRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $section = $sectionRepository->findOneBy(['machineName' => 'own']);
        $posts = $postRepository
            ->createQueryBuilder('p')
            ->join('App:Blog\Section', 's', 'WITH', 'p.section = s.id')
            ->where('p.status = :status')
            ->setParameter(':status', Status::PUBLISH)
            ->andWhere('s.hidden = :hidden')
            ->setParameter(':hidden', Section::NOT_HIDDEN)
            ->orderBy('p.created', 'DESC')
            ->getQuery()
            ->getResult();
        $pagedPosts = $paginator->paginate($posts, $request->query->getInt('page', 1));
        return $this->render("blog/blog.html.twig", ['posts' => $pagedPosts]);
    }

    #[Route("/blog/add", name: ".add", methods: ["GET", "POST"])]
    #[IsGranted("ROLE_ADMIN")]
    public function add(Request $request, Add\Handler $handler): Response
    {
        $form = $this->createForm(PostForm::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $handler->handle(new Add\Command($form->getData()));
            $this->addFlash('notice', 'Post saved');
            return $this->redirectToRoute("blog");
        }
        return $this->render("blog/post-add.html.twig", ['form' => $form->createView()]);
    }

    #[Route("/blog/edit/{post}", name: ".edit", methods: ["GET", "POST"])]
    #[IsGranted("ROLE_ADMIN")]
    public function edit(Post $post, Request $request, Edit\Handler $handler): Response
    {
        $postDTO = PostDTO::createFromPost($post);
        $form = $this->createForm(PostForm::class, $postDTO);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $handler->handle(new Edit\Command($post, $postDTO));
            $this->addFlash('notice', 'Post saved');
            return $this->redirectToRoute("blog.show.from.hru", ['prefix' => $post->getHru()->getPrefix(), 'value' => $post->getHru()->getValue()]);
        }
        return $this->render("blog/post-add.html.twig", ['form' => $form->createView()]);
    }

    #[Route("/blog/{section}", name: ".section", methods: ["GET"], requirements: ["section" => "[a-z]+"])]
    public function section(string $section, PaginatorInterface $paginator, PostRepository $postRepository, Request $request): Response
    {
        $pagedPosts = $paginator->paginate($postRepository->findBySection($section), $request->query->getInt('page', 1));
        return $this->render("blog/blog.html.twig", ['posts' => $pagedPosts]);
    }

    #[Route("/blog/tag/{tag}", name: ".tag", methods: ["GET"], requirements: ["tag" => "^[ёЁA-zА-я0-9 -’]+"], options: ["utf8" => true])]
    public function tag(string $tag, PaginatorInterface $paginator, PostRepository $postRepository, Request $request): Response
    {
        $pagedPosts = $paginator->paginate($postRepository->findByTag($tag), $request->query->getInt('page', 1));
        return $this->render("blog/blog.html.twig", ['posts' => $pagedPosts]);
    }

    #[Route("/blog/show/{post}", name: ".show", methods: ["GET"], requirements: ["post" => "\d+"])]
    public function showPost(Post $post): Response
    {
        if (!is_null($hru = $post->getHru())) {
            return $this->redirectToRoute('blog.show.from.hru', [
                'prefix' => $hru->getPrefix(),
                'value' => $hru->getValue()
            ], Response::HTTP_MOVED_PERMANENTLY);
        }
        if ($post->isPublished() || $this->isGranted("ROLE_ADMIN")) {
            return $this->render('blog/post/show.html.twig', ['post' => $post]);
        }
        $this->addFlash('error', "Post not found.");
        return $this->redirectToRoute('blog');
    }

    #[Route("/blog/list/table", name: ".table", methods: ["GET"])]
    #[IsGranted("ROLE_ADMIN")]
    public function table(PostRepository $postRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $pagedPosts = $paginator->paginate($postRepository->findBy([], ['created' => "DESC"]), $request->query->getInt('page', 1));
        return $this->render("blog/table.html.twig", ['posts' => $pagedPosts]);
    }

    #[Route("/blog/delete/{post}", name: ".delete", methods: ["POST"])]
    #[IsGranted("ROLE_ADMIN")]
    public function delete(Post $post, Request $request, Delete\Handler $handler, TranslatorInterface $translator): Response
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token'))) {
            $this->addFlash("error", $translator->trans("Invalid token"));
        } else {
            $handler->handle($post);
            $this->addFlash('notice', 'Post deleted');
        }
        return $this->redirectToRoute("blog");
    }

    #[Route("/blog/{prefix}/{value}", name: ".show.from.hru", methods: ["GET"])]
    #[Entity("hru", expr: "repository.findOneBy({'prefix': prefix, 'value': value})")]
    #[Entity("post", expr: "repository.findOneBy({'hru': hru})")]
    public function showFromHru(Hru $hru, Post $post): Response
    {
        if ($post->isPublished() || $this->isGranted("ROLE_ADMIN")) {
            return $this->render('blog/post/show.html.twig', ['post' => $post]);
        }
        $this->addFlash('error', "Post not found.");
        return $this->redirectToRoute('blog');
    }
}

templates/blog/blog.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="pl-2 pr-2">
        {% for post in posts %}
            {% if post.hru is not null %}
                {% set post_path = path('blog.show.from.hru', {'prefix': post.hru.prefix, 'value': post.hru.value}) %}
            {% else %}
                {% set post_path = path('blog.show', {'post': post.id} ) %}
            {% endif %}
            <div class="border-bottom clearfix">
                <div class="col-12"><h2 class="mb-0 mt-4"><a href="{{ post_path }}">{{ post.title }}</a></h2></div>
                <div class="col-12"><i><a class="text-dark" href="{{ path('blog.show', {'post': post.id}) }}">{{ post.created|date("d-m-Y H:i") }}</a></i></div>
                <div class="col-12 wordwrap">{{ post.teaser|raw }}</div>
                <div class="col-12 text-right"><a href="{{ post_path }}">{{ 'read more'|trans }}</a></div>
            </div>
        {% endfor %}
        <div class="col-12 pt-2">{{ knp_pagination_render(posts, null, {}, {'align': 'center', 'size': 'small'}) }}</div>
    </div>
{% endblock %}

templates/blog/post-add.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="p-4">
        {{ form_start(form, {'method': 'POST'}) }}
        {{ form_label(form.title, null, {'label_attr': {'class': ''}}) }}
        {{ form_widget(form.title, {'attr': {'class': 'mb-2'}}) }}
        {{ form_label(form.teaser) }}
        {{ form_widget(form.teaser, {'attr': {'class': 'mb-2'}}) }}
        {{ form_label(form.body) }}
        {{ form_widget(form.body, {'attr': {'class': 'mb-2'}}) }}
        {{ form_label(form.section) }}
        {{ form_widget(form.section, {'attr': {'class': 'mb-2'}}) }}
        {{ form_label(form.tags2) }}
        <div class="col-sm-12 p-0 form-inline">
            <input type="text" id="{{ form.tags2.vars.id }}" name="{{ form.tags2.vars.full_name }}" class="w-100" value="{{ form.tags2.vars.value }}" data-tags-url="{{ absolute_url(path('tag.json')) }}">
            {% do form.tags2.setRendered %}
        </div>
        {{ form_label(form.status) }}
        {{ form_widget(form.status, {'attr': {'class': 'mb-2'}}) }}
        <button type="submit" class="btn btn-primary">{{ 'save'|trans }}</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/blog/table.html.twig
{% extends 'base.html.twig' %}
{% set token = csrf_token("delete") %}
{% block body %}
    <div class="p-4">
        <table class="table table-responsive">
            <thead>
            <tr>
                <th class=" p-2 m-0">#</th>
                <th class=" p-2 m-0">{{ 'Title'|trans }}</th>
                <th class=" p-2 m-0">{{ 'Created'|trans }}</th>
                <th class=" p-2 m-0">{{ 'Section'|trans }}</th>
                <th class=" p-2 m-0">{{ 'Author'|trans }}</th>
                <th class=" p-2 m-0">{{ 'Tags'|trans }}</th>
                <th class=" p-2 m-0">{{ 'Actions'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}
                <tr class="{% if post.draft %}background-grey{% endif %}{% if post.removed %}background-dark-grey{% endif %}">
                    <td class=" p-2 m-0">{{ post.id }}</td>
                    <td class=" p-2 m-0"><a class="text-dark" href="{{ path('blog.show', {'post': post.id}) }}">{{ post.title }}</a></td>
                    <td class=" p-2 m-0">{{ post.created|date("d-m-Y H:i") }}</td>
                    <td class=" p-2 m-0">{{ post.section }}</td>
                    <td class=" p-2 m-0">{{ post.author.username }}</td>
                    <td class=" p-2 m-0">
                        <ul class="list-group">
                            {% for tag in post.tags %}
                                <li class="list-group-item p-2 m-0">{{ tag.name }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td class=" p-2 m-0">
                        <ul class="nav nav-pills pb-1">
                            <li class="nav-item p-1">
                                <a class="btn btn-sm bg-primary text-white" href="{{ path('blog.edit', {'post': post.id}) }}">{{ 'Edit'|trans }}</a>
                            </li>
                            <li class="nav-item p-1">
                                <form action="{{ path('blog.delete', {'post': post.id }) }}" class="delete-post-form" method="post">
                                    <input type="hidden" name="token" value="{{ token }}" />
                                    <button type="submit" class="btn btn-danger" data-toggle="confirmation">
                                        <i class="fa fa-trash" aria-hidden="true"></i>{{ 'Remove'|trans }}
                                    </button>
                                </form>
                            </li>
                        </ul>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="col-12 pt-2">{{ knp_pagination_render(posts, null, {}, {'align': 'center', 'size': 'small'}) }}</div>
    </div>
{% endblock %}